warning_threshold: 15

type_body_length:
  warning: 400
  error: 450

disabled_rules:
- trailing_whitespace
- todo

opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - no_fallthrough_only
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - static_operator
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length: 2
  max_length: 
    warning: 40
    error: 100
  excluded:
    - x
    - y

excluded:
- Pods
- Carthage
- ./*/SupportingFiles/Generated

private_outlet:
  allow_private_set: true
